name: Build OTCv8 Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Setup Java JDK
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Setup Android SDK and NDK
      uses: android-actions/setup-android@v2

    - name: Build Android APK
      run: |
        echo "Entrando na pasta client-mobile/android..."
        cd client-mobile/android
        Get-ChildItem
        if (Test-Path "gradlew.bat") {
          .\gradlew assembleDebug
        } else {
          echo "gradlew.bat não encontrado na pasta client-mobile/android!"
          exit 1
        }

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v3
      with:
        name: otcv8-android-apk
        path: client-mobile/android/app/build/outputs/apk/debug/app-debug.apk
